name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: test
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          npm install
          npm run build
          npm run test
