name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: ["0.23.0"]

    name:
    steps:
      - uses: actions/checkout@master
      - name: Test on Deno v${{ matrix.deno }}
        uses: denolib/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - run: deno test --config tsconfig.test.json test/**/*.test.ts test/**/**/*.test.ts test/**/**/**/*.test.ts --allow-net
