name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]
        deno: [v0.23.0]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Deno ${{ matrix.deno }}
        uses: denolib/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - name: npm install, test
        run: |
          npm install
          npm run test:reload
