name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for Deno
        uses: denolib/deno-action@0.19.0
        with:
          args: test --config tsconfig.test.json test/**/*.test.ts test/**/**/*.test.ts test/**/**/**/*.test.ts --allow-net
